on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RSCLOUD_CLIENT_ID: ${ F8545FDD2042477222BF144D92AACC73E294793DEF45C7AD}
      RSCLOUD_CLIENT_SECRET: ${nnJA66ZnXsnA0pXg3cVw0K9iRnS5&#x2F;mA3&#x2F;HL8P7&#x2F;n}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: covr

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
